import Link from "next/link"

export const metadata = {
  title: "FAQ — ChefTable",
  description: "Frequently asked questions about ChefTable.",
}

const faqs = [
  {
    q: "How are recipes generated?",
    a: "Recipes are generated by AI (via Groq) based on your choices: cuisine, skill level, occasion, and how many recipes you want. The AI is prompted to create Michelin-style, technically precise recipes tailored to you.",
  },
  {
    q: "Are recipes unique every time?",
    a: "Yes. Each time you click Generate, the AI creates a new set of recipes. Changing your preferences (e.g. Italian vs French, beginner vs advanced) produces different dishes and instructions.",
  },
  {
    q: "Is my data safe?",
    a: "We use Google OAuth for sign-in (name and email only). We don’t sell your data. Recipe generation sends only your selected preferences and the resulting text to our AI provider. See our Privacy Policy for details.",
  },
  {
    q: "Can I print recipes?",
    a: "Yes. Use “Make Card” on any recipe to open a printable menu card. Use your browser’s Print button (or the Print option in the modal) to save as PDF or print on paper.",
  },
  {
    q: "How does Voice Cook work?",
    a: "Voice Cook reads each recipe step aloud using your device’s built-in text-to-speech. Tap “Voice Cook” on a recipe, then use Prev/Next to move through steps. A timer countdown appears when a step has a suggested time.",
  },
  {
    q: "Is ChefTable free?",
    a: "ChefTable is currently free to use. Sign in with Google, choose your preferences, and generate as many menus as you like. We may introduce optional paid features later; any changes will be communicated clearly.",
  },
]

export default function FAQPage() {
  return (
    <div className="min-h-screen bg-[#0a0908] text-[#ede8e0]">
      <nav className="h-16 flex items-center justify-between px-6 md:px-12 border-b border-[#2e2b26]">
        <Link href="/dashboard" className="text-[#c9a227] font-serif text-xl font-bold tracking-widest hover:text-[#e0bd3a]">
          ChefTable
        </Link>
        <Link href="/dashboard" className="text-sm text-[#b3aa9c] hover:text-[#ede8e0]">
          ← Back to Dashboard
        </Link>
      </nav>
      <main className="max-w-3xl mx-auto px-6 md:px-12 py-10">
        <h1 className="text-3xl font-serif font-bold text-[#c9a227] mb-8">FAQ</h1>

        <div className="space-y-6">
          {faqs.map((faq, i) => (
            <section key={i} className="border-b border-[#2e2b26] pb-6">
              <h2 className="text-base font-semibold text-[#ede8e0] mb-2">{faq.q}</h2>
              <p className="text-sm text-[#b3aa9c] leading-relaxed">{faq.a}</p>
            </section>
          ))}
        </div>
      </main>
    </div>
  )
}
