import Link from "next/link"

export const metadata = {
  title: "About — ChefTable",
  description: "About ChefTable: Michelin-level cooking for everyone.",
}

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-[#0a0908] text-[#ede8e0]">
      <nav className="h-16 flex items-center justify-between px-6 md:px-12 border-b border-[#2e2b26]">
        <Link href="/dashboard" className="text-[#c9a227] font-serif text-xl font-bold tracking-widest hover:text-[#e0bd3a]">
          ChefTable
        </Link>
        <Link href="/dashboard" className="text-sm text-[#b3aa9c] hover:text-[#ede8e0]">
          ← Back to Dashboard
        </Link>
      </nav>
      <main className="max-w-3xl mx-auto px-6 md:px-12 py-10">
        <h1 className="text-3xl font-serif font-bold text-[#c9a227] mb-6">About ChefTable</h1>

        <div className="space-y-6 text-[#ede8e0] text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-[#c9a227] mb-2">What is ChefTable?</h2>
            <p>ChefTable is an AI-powered recipe app that generates Michelin-style menus tailored to your cuisine, skill level, and occasion. You get unique recipes with clear ingredients and steps, plus voice-guided cooking and printable menu cards.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-[#c9a227] mb-2">Our mission</h2>
            <p>We want Michelin-level cooking to be accessible to everyone. Whether you’re a beginner or an experienced cook, ChefTable helps you create restaurant-quality dishes at home with guidance that’s precise, inspiring, and easy to follow.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-[#c9a227] mb-2">Tech in plain English</h2>
            <p>ChefTable is built with Next.js (a modern React framework) and runs on Vercel. You sign in with Google. Recipe text is generated by an AI model (Groq). Voice Cook uses your browser’s built-in speech so you can listen to steps hands-free. No complex setup—just open the app and cook.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-[#c9a227] mb-2">Built by StackDrip</h2>
            <p>ChefTable was built by <a href="mailto:acquisitions@stackdrip.dev" className="text-[#c9a227] hover:underline">StackDrip</a>. For product or partnership enquiries, reach out at acquisitions@stackdrip.dev.</p>
          </section>
        </div>
      </main>
    </div>
  )
}
