import Link from "next/link"

export const metadata = {
  title: "Terms & Conditions — ChefTable",
  description: "ChefTable terms of use and disclaimers.",
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0908] text-[#ede8e0]">
      <nav className="h-16 flex items-center justify-between px-6 md:px-12 border-b border-[#2e2b26]">
        <Link href="/dashboard" className="text-[#c9a227] font-serif text-xl font-bold tracking-widest hover:text-[#e0bd3a]">
          ChefTable
        </Link>
        <Link href="/dashboard" className="text-sm text-[#b3aa9c] hover:text-[#ede8e0]">
          ← Back to Dashboard
        </Link>
      </nav>
      <main className="max-w-3xl mx-auto px-6 md:px-12 py-10">
        <h1 className="text-3xl font-serif font-bold text-[#c9a227] mb-6">Terms & Conditions</h1>
        <p className="text-sm text-[#b3aa9c] mb-8">Last updated: March 2025</p>

        <div className="space-y-6 text-[#ede8e0] text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-[#c9a227] mb-2">Personal use only</h2>
            <p>ChefTable is for personal, non-commercial use. You may use generated recipes and menu cards for your own cooking and household. Redistribution or commercial use of the service or content requires separate permission.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-[#c9a227] mb-2">No guarantee of recipe accuracy</h2>
            <p>Recipes are generated by AI. We do not guarantee nutritional accuracy, allergen completeness, or that following a recipe will produce a specific result. Always use your judgment and follow food-safety practices.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-[#c9a227] mb-2">AI-generated content disclaimer</h2>
            <p>All recipe text, ingredients, and steps are produced by artificial intelligence. They are suggestions only. You are responsible for verifying ingredients, quantities, and methods before cooking.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-[#c9a227] mb-2">User responsibility</h2>
            <p>You are responsible for how you use ChefTable and any outcomes from following generated recipes. We are not liable for any loss, injury, or damage arising from your use of the service.</p>
          </section>
        </div>
      </main>
    </div>
  )
}
